version: '3.4'

services:
  database:
    container_name: postgres-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    image: postgres:13.6
    volumes:
      - database:/var/lib/postgresql/data:Z
    ports:
      - '5432:5432'
volumes:
  database:
