name: code-quality
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v3.0.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install Dependencies
        run: yarn install --immutable
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          filter_mode: nofilter
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v3.0.2
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          exclude: |
            ./yarn.lock
            ./.yarn/*
          locale: 'US'
          level: error
          reporter: github-pr-check
          filter_mode: nofilter
  tests:
    name: runner / test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v3.0.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Run tests
        run: yarn test
