name: deploy-api-service
on:
  push:
    paths:
      - 'services/api/**'
      - '.github/workflows/deploy-api.yml'
    branches:
      - main
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code.
        uses: actions/checkout@v3.0.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Yarn Install
        run: |
          yarn install --immutable
      - name: Export AWS role
        run: |
          echo "DEPLOYMENT_ROLE=$(yarn dlx -q ts-node ./scripts/print-aws-role.ts --environment staging --service api)" >> $GITHUB_ENV
      - name: Configure AWS credentials from staging account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.DEPLOYMENT_ROLE }}
          aws-region: eu-central-1
      - name: Deploy api
        working-directory: services/api
        run: |
          yarn deploy:staging
  deploy-production:
    needs:
      - deploy-staging
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code.
        uses: actions/checkout@v3.0.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Yarn Install
        run: |
          yarn install --immutable
      - name: Export AWS role
        run: |
          echo "DEPLOYMENT_ROLE=$(yarn dlx -q ts-node ./scripts/print-aws-role.ts --environment production --service api)" >> $GITHUB_ENV
      - name: Configure AWS credentials from production account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.DEPLOYMENT_ROLE }}
          aws-region: eu-central-1
      - name: Deploy api
        working-directory: services/api
        run: |
          yarn deploy:production
