name: deployment
on:
  push:
    branches:
      - main
jobs:
  ################################
  ## Deploy to staging
  ################################

  provision-infrastructure-staging:
    name: deploy staging infrastructure
    uses: ./provision-infrastructure.yml@main
    with:
      environment: staging

  deploy-api-staging:
    needs: provision-staging-infrastructure
    name: deploy api production
    uses: ./deploy-api.yml@main
    with:
      environment: staging

  deploy-webapp-staging:
    needs: provision-staging-infrastructure
    name: deploy webapp staging
    uses: ./deploy-webapp.yml@main
    with:
      environment: staging

  ################################
  ## Deploy to production
  ################################

  provision-infrastructure-production:
    needs:
      - deploy-api-staging
      - deploy-webapp-staging
    name: provision production infrastructure
    uses: ./provision-infrastructure.yml@main
    with:
      environment: production

  deploy-api-production:
    name: deploy api production
    needs: provision-infrastructure-production
    uses: ./deploy-api.yml@main
    with:
      environment: production

  deploy-webapp-production:
    name: deploy webapp production
    needs: provision-infrastructure-production
    uses: ./deploy-webapp.yml@main
    with:
      environment: production
