name: deployment
on:
  push:
    branches:
      - main
jobs:
  deploy-webapp-staging:
    name: deploy webapp staging
    uses: ./deploy-webapp.yml@main
    with:
      environment: staging

  deploy-webapp-production:
    name: deploy webapp production
    needs: deploy-webapp-staging
    uses: ./deploy-webapp.yml@main
    with:
      environment: production

  deploy-api-staging:
    name: deploy api production
    uses: ./deploy-api.yml@main
    with:
      environment: staging

  deploy-api-production:
    name: deploy webapp production
    needs: deploy-api-staging
    uses: ./deploy-api.yml@main
    with:
      environment: production
