name: deployment
on:
  push:
    branches:
      - main
jobs:
  deploy-webapp-staging:
    uses: volca-io/volca/.github/workflows/deploy-webapp.yml@main
    with:
      environment: staging

  deploy-webapp-production:
    needs: deploy-webapp-staging
    uses: volca-io/volca/.github/workflows/deploy-webapp.yml@main
    with:
      environment: production

  deploy-api-staging:
    uses: volca-io/volca/.github/workflows/deploy-api.yml@main
    with:
      environment: staging

  deploy-api-production:
    needs: deploy-api-staging
    uses: volca-io/volca/.github/workflows/deploy-api.yml@main
    with:
      environment: production
