name: deploy
on:
  push:
    branches:
      - main
jobs:
  ################################
  ## Deploy to staging
  ################################

  deploy-certificates-staging:
    permissions:
      id-token: write
      contents: read
    name: deploy certificates staging
    uses: ./.github/workflows/deploy-certificates.yml
    with:
      environment: staging

  deploy-api-staging:
    needs: deploy-certificates-staging
    permissions:
      id-token: write
      contents: read
    name: deploy api staging
    uses: ./.github/workflows/deploy-api.yml
    with:
      environment: staging

  deploy-webapp-staging:
    needs: deploy-certificates-staging
    permissions:
      id-token: write
      contents: read
    name: deploy webapp staging
    uses: ./.github/workflows/deploy-webapp.yml
    with:
      environment: staging

  ################################
  ## Deploy to production
  ################################

  deploy-certificates-production:
    permissions:
      id-token: write
      contents: read
    name: deploy certificates production
    uses: ./.github/workflows/deploy-certificates.yml
    needs:
      - deploy-api-staging
      - deploy-webapp-staging
    with:
      environment: production

  deploy-api-production:
    permissions:
      id-token: write
      contents: read
    name: deploy api production
    needs: deploy-certificates-production
    uses: ./.github/workflows/deploy-api.yml
    with:
      environment: production

  deploy-webapp-production:
    permissions:
      id-token: write
      contents: read
    name: deploy webapp production
    needs: deploy-certificates-production
    uses: ./.github/workflows/deploy-webapp.yml
    with:
      environment: production
