name: deploy
on:
  push:
    branches:
      - main
jobs:
  ################################
  ## Deploy to staging
  ################################

  provision-infrastructure-staging:
    permissions:
      id-token: write
      contents: read
    name: deploy staging infrastructure
    uses: ./.github/workflows/provision-infrastructure.yml
    with:
      environment: staging

  deploy-api-staging:
    permissions:
      id-token: write
      contents: read
    needs: provision-infrastructure-staging
    name: deploy api production
    uses: ./.github/workflows/deploy-api.yml
    with:
      environment: staging

  deploy-webapp-staging:
    permissions:
      id-token: write
      contents: read
    needs: provision-infrastructure-staging
    name: deploy webapp staging
    uses: ./.github/workflows/deploy-webapp.yml
    with:
      environment: staging

  ################################
  ## Deploy to production
  ################################

  provision-infrastructure-production:
    permissions:
      id-token: write
      contents: read
    needs:
      - deploy-api-staging
      - deploy-webapp-staging
    name: provision production infrastructure
    uses: ./.github/workflows/provision-infrastructure.yml
    with:
      environment: production

  deploy-api-production:
    permissions:
      id-token: write
      contents: read
    name: deploy api production
    needs: provision-infrastructure-production
    uses: ./.github/workflows/deploy-api.yml
    with:
      environment: production

  deploy-webapp-production:
    permissions:
      id-token: write
      contents: read
    name: deploy webapp production
    needs: provision-infrastructure-production
    uses: ./.github/workflows/deploy-webapp.yml
    with:
      environment: production
