name: provision-infrastructure
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code.
        uses: actions/checkout@v3.0.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Yarn Install
        run: |
          yarn install --immutable
      - name: Configure AWS credentials from ${{ inputs.environment }}  account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/${{ env.APPLICATION_NAME }}-${{ inputs.environment }}-github-actions-api-deployment-role
          aws-region: ${{ env.AWS_REGION }}
      - name: Provision infrastructure
        run: |
          yarn infra:deploy --stage ${{ inputs.environment }}
